modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="lancemod"
version="0.0.1"
displayName="兰斯模组"
credits="MCreatort，LNGS，HuanMeng"
displayURL="https://space.bilibili.com/626446902"
authors="LNGS,HuanMeng, MCreator"

[[dependencies.lancemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




